### ISSUE TITLE
ROS Lunar Release

### ISSUE THREAD

**Issue by allenh1** [ros-perception/openslam_gmapping#17]
Please release this package for Lunar!

**Comment by mikaelarguedas** [comment]
Howdy @vrabaud,

Any update on this ? now that navigation is released, SLAM packages would be awesome to have

**Comment by vrabaud** [comment]
And done, https://github.com/ros/rosdistro/pull/15710

**Comment by allenh1** [comment]
Thanks!

**Comment by mikaelarguedas** [comment]
thanks @vrabaud !
