### ISSUE TITLE
question about git source and ros-kinetic-openslam

### ISSUE THREAD

**Issue by JunGooLee** [ros-perception/openslam_gmapping#26]
is there are same the source code? (in here git source & ros-kinetic-openslam )
I learn about openslam gmapping and check the operation (iteration) loop time both of them.
that's why there operation loop time is difference.
It would see something difference...
Now I checking about parameter setting... but I do not know yet what is there difference.

**Comment by shanpenghui** [comment]
i also met the same problem, have you resolved it ?

**Comment by shanpenghui** [comment]
I install the ros-kinetic-openslam-gmapping with the version 0.1.2-0xenial-20190607-165010-0800.
And i download the git source , and compiled with master version.
The result is difference. The installed one is working, but the source is not working well. I do not where is the difference.

**Comment by k-okada** [comment]
you can download 0.1.2 of gmapping from 
```
git clone https://github.com/ros-perception/openslam_gmapping -b master
```
and that is different from latest source (0.2.1) because of updating to BSD version of gmapping (c.f. 
https://github.com/ros-perception/openslam_gmapping/pull/29 )

if there is difference (specially regressions) between 0.1.2 and 0.2.1, let me know.
