### ISSUE TITLE
License reassigned from CC to BSD

### ISSUE THREAD

**Issue by SteveMacenski** [ros-perception/openslam_gmapping#31]
In commit a91e670b1a0f2e10bab7750d1da9f844266777e5 the license was changed from `CreativeCommons-by-nc-sa-2.0`

https://github.com/ros-perception/openslam_gmapping/blob/master/package.xml#L6

to `BSD`

https://github.com/ros-perception/openslam_gmapping/commit/a91e670b1a0f2e10bab7750d1da9f844266777e5#diff-34ae68f4adad56c25c5bc05dcb64794eR8

Which seems like a mistake. Should this be reverted?

**Comment by k-okada** [comment]
no this is what I expected, the license is now BSD, see ->
https://github.com/ros-perception/openslam_gmapping/pull/20
--
◉ Kei Okada



2019年9月17日(火) 7:00 Steven Macenski <notifications@github.com>:
