### ISSUE TITLE
Release openslam_gmapping into ROS Noetic?

### ISSUE THREAD

**Issue by sloretz** [ros-perception/openslam_gmapping#32]
Would you mind releasing `openslam_gmapping` to ROS Noetic? It looks like all of its dependencies have been released, and recursively 14 repos need it.

I'm not sure how much work it will need. The [Noetic Migration Guide](http://wiki.ros.org/noetic/Migration) or the [guide about transitioning ROS packages to Python 3](http://wiki.ros.org/UsingPython3/) may be useful.

**Comment by k-okada** [comment]
thanks released  https://github.com/ros/rosdistro/pull/24598
--
◉ Kei Okada



2020年4月24日(金) 2:25 Shane Loretz <notifications@github.com>:

**Comment by PranshuTople** [comment]
@k-okada how to install this package??? the noetic version?

P.S. - I am new to this, so please explain in detail

**Comment by k-okada** [comment]
you need to install ros/noetic first, then install gmapping. (http://wiki.ros.org/noetic/Installation/Ubuntu)

```
sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
sudo apt-key adv --keyserver 'hkp://keyserver.ubuntu.com:80' --recv-key C1CF6E31E6BADE8868B172B4F42ED6FBAB17C654
sudo apt update
sudo apt install ros-noetic-slam-gmapping
```
